# Generated by Django 4.0.3 on 2022-05-14 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queimada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=11)),
                ('brightness', models.CharField(max_length=7)),
                ('scan', models.CharField(max_length=5)),
                ('track', models.CharField(max_length=5)),
                ('acq_date', models.CharField(max_length=11)),
                ('acq_time', models.CharField(max_length=5)),
                ('satellite', models.CharField(max_length=2)),
                ('instrument', models.CharField(max_length=6)),
                ('confidence', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
                ('bright_t31', models.CharField(max_length=7)),
                ('frp', models.CharField(max_length=7)),
                ('daynight', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=2)),
                ('altitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
